stages:
  - build-dev
  - deploy-dev
  - build-hom
  - deploy-hom
  - build-prd
  - deploy-prd

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-dev:
  stage: build-dev
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    refs:
      - develop
  tags:
    - dev

build-hom:
  stage: build-hom
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    refs:
      - homolog
  tags:
    - hom

build-prd:
  stage: build-prd
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    refs:
      - main
  tags:
    - prd

deploy-dev:
  stage: deploy-dev
  script:
    - cp ./docker/.env.dev .env
    - docker compose down
    - docker compose up -d
  only:
    refs:
      - develop
  tags:
    - dev

deploy-hom:
  stage: deploy-hom
  script:
    - cp ./docker/.env.hom .env
    - docker compose down
    - docker compose up -d
  only:
    refs:
      - homolog
  tags:
    - hom

deploy-prd:
  stage: deploy-prd
  script:
    - cp ./docker/.env.prd .env
    - docker compose down
    - docker compose up -d
  only:
    refs:
      - main
  tags:
    - prd
